// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "d3ceb161cfab9e9c5f40a93e15e5be27"
    },
    {
        "url": "index.html",
        "revision": "13fce47f713f606fe1f8339185ab9e21"
    },
    {
        "url": "index3.html",
        "revision": "6383069929b9b4a1962358bb37d620be"
    },
    {
        "url": "index4Best.html",
        "revision": "1a1847ac92f68f5cb7ced3327923933e"
    },
    {
        "url": "index5.html",
        "revision": "7a34bca71e234293ecb1ababcdcb991c"
    },
    {
        "url": "indexBest.html",
        "revision": "2b28e69076c555c3ff79acb23b3ce8d4"
    },
    {
        "url": "manifest.json",
        "revision": "d5fdf318e01e29220eca36f33f88ab55"
    },
    {
        "url": "offline.html",
        "revision": "ad17d01f02bb01615fbc0509f5aee82a"
    },
    {
        "url": "pwa-register.js",
        "revision": "3ec872e4f752840ad8f85922ff6cebe7"
    },
    {
        "url": "readme.md",
        "revision": "06157c2ad610b40ed48802008ccfd4e4"
    },
    {
        "url": "safeer.png",
        "revision": "b6ada0cbd309c0fc5deebc14bd2c79b9"
    },
    {
        "url": "safeer2.PNG",
        "revision": "add12a579844df24591c805f484f737a"
    },
    {
        "url": "sw.js",
        "revision": "21d3f2fd649962e311f7ad12888bde3a"
    },
    {
        "url": "test.html",
        "revision": "41e4a698e8bdd0122a9f1dd0d27f2089"
    },
    {
        "url": "_indexnew_main.js",
        "revision": "98186d2814fbd596173af04479a7740f"
    },
    {
        "url": "_index_diff.txt",
        "revision": "99e7fe921903291b0e25dce0024d4f07"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}